spring:
#  thymeleaf:
#    cache: false
#  template:
#    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    view:
      prefix: /
      suffix: .jsp
    favicon:
      enabled: false
    static-path-pattern:
      - /static/**
      - /webjars/**
  resources:
    static-locations:
      - classpath:/static/
      - classpath:/META-INF/resources/webjars/
  datasource:
    url: jdbc:mysql://localhost:3306/courseselection?useSSL=false&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 10000
  application:
    name: courses
mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8888
  servlet:
#    context-path: /courses
    jsp:
      init-parameters:
        development: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql